package encembed

const tpl = `// Code generated by 'go generate'; DO NOT EDIT.
package {{.PkgName}}

import(
	"filippo.io/age"
	"io"
	_ "embed"
	"bytes"
)

//go:embed {{.EmbedName}}
var {{.EncryptedVarName}} []byte
func {{.FuncName}}({{if .ExternalKey}}key string{{end}}) []byte {
	i, _ := age.NewScryptIdentity({{if .ExternalKey}}key{{else}}"{{.Key}}"{{end}})
	r, _ := age.Decrypt(bytes.NewReader({{.EncryptedVarName}}), i)
	a, _ := io.ReadAll(r)
	return a
}
{{if .DecryptedVarName}}var {{.DecryptedVarName}} = {{.FuncName}}() {{end}}
`
